import * as dotenv from 'dotenv';
dotenv.config();

import prisma from '../src/config/db';

// ─── Helpers ────────────────────────────────────────────────────────────────

function parseTime(hoursStr: string): { open: string; close: string } {
  if (hoursStr.toLowerCase().includes("open 24")) {
    return { open: "00:00", close: "23:59" };
  }
  const match = hoursStr.match(/(\d{1,2}:\d{2}\s?[AP]M)\s*[–-]\s*(\d{1,2}:\d{2}\s?[AP]M)/i);
  if (!match || !match[1] || !match[2]) return { open: "10:00", close: "23:00" };
  
  const to24 = (t: string) => {
    const parts = t.trim().split(/\s/);
    const time = parts[0] || "10:00";
    const meridiem = parts[1] || "AM";
    
    let [hStr, mStr] = time.split(":");
    let h = Number(hStr) || 10;
    let m = Number(mStr) || 0;
    
    if (meridiem.toUpperCase() === "PM" && h !== 12) h += 12;
    if (meridiem.toUpperCase() === "AM" && h === 12) h = 0;
    return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}`;
  };
  return { open: to24(match[1]), close: to24(match[2]) };
}

// ─── Raw scraped data ────────────────────────────────────────────────────────

interface RawClub {
  name: string;
  address: string;
  area: string;
  city: string;
  lat: number;
  lng: number;
  rating: number;
  phone: string | null;
  openingHours: string;
  snookerTables: number | null;
  poolTables: number | null;
  snookerPricePerHour: number;
  poolPricePerHour: number;
  amenities: string[];
}

const clubs: RawClub[] = [
  // ── Delhi ────────────────────────────────────────────────────────────────
  {
    name: "CueDue Snooker Cafe",
    address: "G 72, Jaswant Plaza, Kalindi Kunj Rd, Shaheen Bagh, Okhla, New Delhi, Delhi 110025",
    area: "Shaheen Bagh, Okhla",
    city: "New Delhi",
    lat: 28.5438412,
    lng: 77.3041678,
    rating: 4.7,
    phone: "+91 99902 20197",
    openingHours: "Open 24 hours",
    snookerTables: 7,
    poolTables: 1,
    snookerPricePerHour: 300,
    poolPricePerHour: 200,
    amenities: ["AC", "Snacks & Drinks", "VIP Lounge", "Practice Room", "WiFi"],
  },
  {
    name: "Snooker Club 147",
    address: "B-1, 2nd Floor, Neeraj Medical, Bindapur Rd, Sanjay Enclave, Uttam Nagar, Delhi 110059",
    area: "Uttam Nagar",
    city: "New Delhi",
    lat: 28.6145558,
    lng: 77.059240,
    rating: 4.9,
    phone: "+91 96256 20955",
    openingHours: "Open 24 hours",
    snookerTables: 4,
    poolTables: 2,
    snookerPricePerHour: 250,
    poolPricePerHour: 200,
    amenities: ["AC", "Food Available", "24/7"],
  },
  {
    name: "Asif Snooker Club",
    address: "H73V+2XR, Part 1 Abul Fazal Enclave, Jamia Nagar, Okhla, New Delhi, Delhi 110025",
    area: "Jamia Nagar, Okhla",
    city: "New Delhi",
    lat: 28.5526245,
    lng: 77.2948866,
    rating: 4.2,
    phone: "+91 96542 48497",
    openingHours: "Open 24 hours",
    snookerTables: 5,
    poolTables: 1,
    snookerPricePerHour: 250,
    poolPricePerHour: 200,
    amenities: ["AC", "Canteen", "WiFi", "Clean Washrooms", "Star Tables"],
  },
  {
    name: "Big Billiards",
    address: "10 Basement, Outer Ring Rd, Pocket GH2, Bhera Enclave, Paschim Vihar, New Delhi, Delhi 110087",
    area: "Paschim Vihar",
    city: "New Delhi",
    lat: 28.6717906,
    lng: 77.0936227,
    rating: 4.9,
    phone: "+91 98716 20491",
    openingHours: "12:00 PM – 4:00 AM",
    snookerTables: 3,
    poolTables: 2,
    snookerPricePerHour: 300,
    poolPricePerHour: 200,
    amenities: ["AC", "Food & Drinks", "Premium Ambience"],
  },
  {
    name: "Megapool Snooker Academy",
    address: "224 Dada Dev Tower 2nd Floor, Behind Akash Hospital, Rajapuri Chowk, Dwarka, New Delhi, Delhi 110059",
    area: "Dwarka",
    city: "New Delhi",
    lat: 28.6051139,
    lng: 77.0543445,
    rating: 4.3,
    phone: "+91 78610 00999",
    openingHours: "Open 24 hours",
    snookerTables: 2,
    poolTables: 1,
    snookerPricePerHour: 250,
    poolPricePerHour: 200,
    amenities: ["AC", "Snacks & Coffee", "Coaching", "24/7"],
  },
  {
    name: "Smash Snooker Club and Cafe",
    address: "Block B, Sant Nagar, Burari, Delhi 110084",
    area: "Burari",
    city: "New Delhi",
    lat: 28.739365,
    lng: 77.1978242,
    rating: 5.0,
    phone: null,
    openingHours: "Open 24 hours",
    snookerTables: 3,
    poolTables: 1,
    snookerPricePerHour: 200,
    poolPricePerHour: 150,
    amenities: ["Food & Drinks", "24/7", "Nice Ambience"],
  },
  {
    name: "Sahil Snooker Club",
    address: "TA 208, Guru Ravidas Marg, near Hanuman Mandir, Kalkaji Extension, Kalkaji, New Delhi, Delhi 110019",
    area: "Kalkaji",
    city: "New Delhi",
    lat: 28.52819,
    lng: 77.2578981,
    rating: 5.0,
    phone: "+91 85272 54164",
    openingHours: "Open 24 hours",
    snookerTables: 4,
    poolTables: 1,
    snookerPricePerHour: 250,
    poolPricePerHour: 200,
    amenities: ["AC", "Clean Environment", "Good Lighting", "24/7"],
  },
  {
    name: "Jalwa Billiards & Cafe",
    address: "Building no. 1211, Chah Rahat, Wakilpura Behind Bukhara Hotel, Near Jama Masjid Gate no.3, Chandni Chowk, New Delhi, Delhi 110006",
    area: "Chandni Chowk",
    city: "New Delhi",
    lat: 28.6519902,
    lng: 77.2326675,
    rating: 4.3,
    phone: "+91 99533 69874",
    openingHours: "3:00 PM – 3:00 AM",
    snookerTables: 2,
    poolTables: 1,
    snookerPricePerHour: 225,
    poolPricePerHour: 175,
    amenities: ["Fast Food", "Late Night", "Casual Vibe"],
  },
  {
    name: "8 Balls Gaming Club",
    address: "Second Floor, Kh.No 33/24, opposite True Value Showroom, Pocket 3, Sector 17, Rohini, Delhi 110089",
    area: "Rohini Sector 17",
    city: "New Delhi",
    lat: 28.7435295,
    lng: 77.1215383,
    rating: 5.0,
    phone: null,
    openingHours: "11:00 AM – 11:30 PM",
    snookerTables: 2,
    poolTables: 3,
    snookerPricePerHour: 200,
    poolPricePerHour: 150,
    amenities: ["Snacks", "Family Friendly", "Good Lighting"],
  },
  {
    name: "SnookerWala",
    address: "Lower G. Floor, Sachdeva Corporate Tower, Under South Indian Bank, near BP Petrol Pump, Sector 8, Rohini, Delhi 110085",
    area: "Rohini Sector 8",
    city: "New Delhi",
    lat: 28.7028896,
    lng: 77.1227999,
    rating: 4.8,
    phone: "+91 96542 36476",
    openingHours: "9:30 AM – 5:00 AM",
    snookerTables: 5,
    poolTables: 2,
    snookerPricePerHour: 300,
    poolPricePerHour: 200,
    amenities: ["AC", "Drinks", "Late Night", "Premium Ambience"],
  },
  {
    name: "Baba Billiards Academy",
    address: "Metro Pillar No. 72, Basement of Senco Gold Jewellers, 4, Bharti Artist Colony Rd, Nirman Vihar, Preet Vihar, Delhi 110092",
    area: "Nirman Vihar, Preet Vihar",
    city: "New Delhi",
    lat: 28.6372339,
    lng: 77.2884082,
    rating: 4.2,
    phone: "+91 98114 25782",
    openingHours: "Open 24 hours",
    snookerTables: 5,
    poolTables: 1,
    snookerPricePerHour: 240,
    poolPricePerHour: 200,
    amenities: ["AC", "Canteen", "Coaching", "24/7"],
  },

  // ── Gurgaon ──────────────────────────────────────────────────────────────
  {
    name: "Sai Pool and Snooker Parlour Club",
    address: "1163p, Sector Main Rd, Block E, Sector 46, Gurugram, Haryana 122003",
    area: "Sector 46",
    city: "Gurugram",
    lat: 28.4376332,
    lng: 77.0584036,
    rating: 4.6,
    phone: "+91 90501 13111",
    openingHours: "Open 24 hours",
    snookerTables: 4,
    poolTables: 2,
    snookerPricePerHour: 300,
    poolPricePerHour: 200,
    amenities: ["AC", "24/7", "Clean Environment"],
  },
  {
    name: "Hall Of Frames – Snooker and Pool Club",
    address: "Basement, Plot No-107, near Metro Station Phase 1, Sector 28, Chakkarpur, Gurugram, Haryana 122009",
    area: "Sector 28, Chakkarpur",
    city: "Gurugram",
    lat: 28.4699426,
    lng: 77.0923865,
    rating: 4.7,
    phone: "+91 85950 26461",
    openingHours: "Open 24 hours",
    snookerTables: 4,
    poolTables: 2,
    snookerPricePerHour: 300,
    poolPricePerHour: 200,
    amenities: ["AC", "24/7", "Family Friendly", "Premium Tables"],
  },
  {
    name: "Pockets Snooker Club",
    address: "Sco 1, Dayal Market, Urban Estate, Gurgaon Rural, Gurugram, Haryana 122001",
    area: "Gurgaon Rural",
    city: "Gurugram",
    lat: 28.4699247,
    lng: 77.0143518,
    rating: 4.9,
    phone: "+91 98719 10410",
    openingHours: "Open 24 hours",
    snookerTables: 5,
    poolTables: 2,
    snookerPricePerHour: 350,
    poolPricePerHour: 250,
    amenities: ["AC", "24/7", "Professional Tables", "Clean Premises"],
  },
  {
    name: "7/11 Billiards & Lounge",
    address: "240, Sector Rd, Sector 51, Gurugram, Haryana 122018",
    area: "Sector 51",
    city: "Gurugram",
    lat: 28.433732,
    lng: 77.066155,
    rating: 4.6,
    phone: "+91 92054 35583",
    openingHours: "12:00 PM – 5:00 AM",
    snookerTables: 3,
    poolTables: 2,
    snookerPricePerHour: 300,
    poolPricePerHour: 200,
    amenities: ["AC", "Canteen", "PS5", "Table Tennis", "Late Night"],
  },
  {
    name: "Anytime Snooker Club and Cafe",
    address: "City Emporio, New Colony More, Old Railway Rd, near Raj Mahal Hotel, Sector 7, Gurugram, Haryana 122001",
    area: "Sector 7",
    city: "Gurugram",
    lat: 28.4671103,
    lng: 77.0206523,
    rating: 5.0,
    phone: "+91 88004 37147",
    openingHours: "Open 24 hours",
    snookerTables: 4,
    poolTables: 2,
    snookerPricePerHour: 250,
    poolPricePerHour: 150,
    amenities: ["AC", "24/7", "Coaching", "Budget Friendly"],
  },
  {
    name: "Golden Break Snooker Club",
    address: "42, U-12 Rd, U Block, DLF Phase 3, Sector 24, Gurugram, Haryana 122002",
    area: "DLF Phase 3, Sector 24",
    city: "Gurugram",
    lat: 28.4941161,
    lng: 77.0947763,
    rating: 4.5,
    phone: "+91 88001 82869",
    openingHours: "Open 24 hours",
    snookerTables: 2,
    poolTables: 2,
    snookerPricePerHour: 300,
    poolPricePerHour: 200,
    amenities: ["AC", "24/7", "Music", "Late Night"],
  },

  // ── Noida ─────────────────────────────────────────────────────────────────
  {
    name: "Cue Club",
    address: "AMALTASH MARG, plot no 4, above Citizen Co-op Bank, Sector 22, Noida, Uttar Pradesh 201307",
    area: "Sector 22",
    city: "Noida",
    lat: 28.5946609,
    lng: 77.3426279,
    rating: 3.8,
    phone: "+91 98912 77774",
    openingHours: "Open 24 hours",
    snookerTables: 4,
    poolTables: 2,
    snookerPricePerHour: 150,
    poolPricePerHour: 100,
    amenities: ["Big Screen TV", "24/7", "Female Friendly"],
  },
  {
    name: "The Snooker Central",
    address: "4th Floor, CMC Complex, M 7, Dadri Main Rd, Sector 49, Noida, Uttar Pradesh 201304",
    area: "Sector 49",
    city: "Noida",
    lat: 28.5606138,
    lng: 77.3691485,
    rating: 4.7,
    phone: "+91 88605 77577",
    openingHours: "11:00 AM – 11:00 PM",
    snookerTables: 5,
    poolTables: 2,
    snookerPricePerHour: 330,
    poolPricePerHour: 250,
    amenities: ["AC", "Food Menu", "Premium Tables", "Sports Equipment Shop"],
  },
  {
    name: "House of Billiards",
    address: "Gate no 2, SD-09 Basement, near Sector 116 Main Road, Sector 116, Noida, Uttar Pradesh 201309",
    area: "Sector 116",
    city: "Noida",
    lat: 28.5687776,
    lng: 77.3952236,
    rating: 4.8,
    phone: "+91 99600 35617",
    openingHours: "11:00 AM – 11:00 PM",
    snookerTables: 6,
    poolTables: 2,
    snookerPricePerHour: 300,
    poolPricePerHour: 200,
    amenities: ["AC", "Coaching", "Food", "Professional Tables"],
  },
  {
    name: "The Hangout Club",
    address: "Bus Stand, I-20, Block I, Sector 22, Noida, Uttar Pradesh 201307",
    area: "Sector 22",
    city: "Noida",
    lat: 28.5986156,
    lng: 77.3449455,
    rating: 4.1,
    phone: "+91 98710 34492",
    openingHours: "10:00 AM – 10:00 PM",
    snookerTables: 6,
    poolTables: 4,
    snookerPricePerHour: 220,
    poolPricePerHour: 150,
    amenities: ["AC", "Smoking Zone", "Multiple Tables", "Parking"],
  },
  {
    name: "The Snook",
    address: "3rd Floor, Ashirwad Complex, Ghijore, Sector 53, Noida, Uttar Pradesh 201307",
    area: "Sector 53",
    city: "Noida",
    lat: 28.586531,
    lng: 77.3632212,
    rating: 4.3,
    phone: "+91 96546 03906",
    openingHours: "11:00 AM – 1:00 AM",
    snookerTables: 2,
    poolTables: 2,
    snookerPricePerHour: 250,
    poolPricePerHour: 180,
    amenities: ["Snacks", "Parking", "Late Night"],
  },

  // ── Greater Noida ─────────────────────────────────────────────────────────
  {
    name: "6 Flags Snooker Club & Restaurant",
    address: "3/1B, Knowledge Park III, Greater Noida, Uttar Pradesh 201308",
    area: "Knowledge Park III",
    city: "Greater Noida",
    lat: 28.4770707,
    lng: 77.4914632,
    rating: 4.7,
    phone: "+91 99990 80337",
    openingHours: "10:00 AM – 1:00 AM",
    snookerTables: 6,
    poolTables: 2,
    snookerPricePerHour: 350,
    poolPricePerHour: 250,
    amenities: ["Restaurant", "AC", "PS5", "Foosball", "Outdoor Seating", "Bonfire in Winter", "Coaching"],
  },


  //Faridabad & New Delhi
  {
    name: "Pool World",
    address: "101, Basement, NH-5, Railway Rd, CBI Colony, New Industrial Township, Faridabad, Haryana 121001",
    area: "New Industrial Township",
    city: "Faridabad",
    lat: 28.4030617,
    lng: 77.3059426,
    rating: 4.9,
    phone: null,
    openingHours: "10:00 AM – 6:00 AM",
    snookerTables: 4,
    poolTables: 3,
    snookerPricePerHour: 250,
    poolPricePerHour: 180,
    amenities: ["Food & Drinks", "Late Night", "Snacks", "Cigarettes at MRP"],
  },
  {
    name: "The Cue Casa",
    address: "Bake Mart Basement, near Bansal Dhaba, Huda Market, Inder Colony, Sector 31, Faridabad, Haryana 121003",
    area: "Sector 31",
    city: "Faridabad",
    lat: 28.4459462,
    lng: 77.3171139,
    rating: 4.8,
    phone: "+91 81309 81542",
    openingHours: "Open 24 hours",
    snookerTables: 3,
    poolTables: 2,
    snookerPricePerHour: 250,
    poolPricePerHour: 180,
    amenities: ["AC", "24/7", "Food", "Female Friendly", "Safe Environment"],
  },
  {
    name: "The Cue's Snooker Room",
    address: "2n 74, Block N, New Industrial Twp 2, New Industrial Township, Faridabad, Haryana 121001",
    area: "New Industrial Township 2",
    city: "Faridabad",
    lat: 28.3893151,
    lng: 77.2898539,
    rating: 4.5,
    phone: "+91 78278 78787",
    openingHours: "Open 24 hours",
    snookerTables: 3,
    poolTables: 3,
    snookerPricePerHour: 180,
    poolPricePerHour: 100,
    amenities: ["24/7", "Budget Friendly", "Large Capacity"],
  },
  {
    name: "The Green Room – Snooker and Pool Club",
    address: "Plot no. 25, 88 Dividing Road, opposite Chandiwala Bagh, Sector 87, Neharpar Faridabad, Haryana 121002",
    area: "Sector 87, Neharpar",
    city: "Faridabad",
    lat: 28.4192702,
    lng: 77.3499737,
    rating: 5.0,
    phone: "+91 83739 38384",
    openingHours: "11:00 AM – 10:00 PM",
    snookerTables: 3,
    poolTables: 1,
    snookerPricePerHour: 250,
    poolPricePerHour: 180,
    amenities: ["Premium Tables", "Clean Environment", "Good Ambience"],
  },
  {
    name: "DoubleBlack Snooker Club",
    address: "Anshu Properties Basement, A-1870, Mall Rd, opposite Bikaner House, Greenfield Colony, Sector 43, Faridabad, Haryana 121010",
    area: "Sector 43, Greenfield Colony",
    city: "Faridabad",
    lat: 28.4623885,
    lng: 77.2981527,
    rating: 4.9,
    phone: null,
    openingHours: "Open 24 hours",
    snookerTables: 3,
    poolTables: 2,
    snookerPricePerHour: 280,
    poolPricePerHour: 200,
    amenities: ["AC", "24/7", "Café", "New Quality Tables", "Outside Food Allowed"],
  },
  {
    name: "Sticks & Balls Snooker and Pool Club",
    address: "Chandila Chowk, Bathola, Bhataula Village, Sector 82, Faridabad, Haryana 121007",
    area: "Sector 82, Bhataula",
    city: "Faridabad",
    lat: 28.3883577,
    lng: 77.3604835,
    rating: 4.8,
    phone: "+91 79060 98211",
    openingHours: "11:00 AM – 12:00 AM",
    snookerTables: 4,
    poolTables: 3,
    snookerPricePerHour: 250,
    poolPricePerHour: 180,
    amenities: ["World Class Tables", "Water & Cold Drinks", "Spacious"],
  },
  {
    name: "AK147",
    address: "130, Basement, Sector 21C, Faridabad, Haryana 121003",
    area: "Sector 21C",
    city: "Faridabad",
    lat: 28.4319922,
    lng: 77.2968531,
    rating: 5.0,
    phone: null,
    openingHours: "10:00 AM – 11:00 PM",
    snookerTables: 3,
    poolTables: 2,
    snookerPricePerHour: 250,
    poolPricePerHour: 180,
    amenities: ["AC", "Music", "Clean", "Friendly Staff"],
  },
  {
    name: "Planet Pool & Snooker",
    address: "Plot No. 87, Sapna Market, 12/2, Sarai Khawaja Village, Sector 37, Faridabad, Haryana 121003",
    area: "Sector 37",
    city: "Faridabad",
    lat: 28.480961,
    lng: 77.3061268,
    rating: 4.6,
    phone: "+91 93157 63370",
    openingHours: "Open 24 hours",
    snookerTables: 2,
    poolTables: 2,
    snookerPricePerHour: 200,
    poolPricePerHour: 150,
    amenities: ["24/7"],
  },

  // ══════════════════════════════════════════════════════════════
  //  NEW DELHI – Central / South / East / North (new areas)
  // ══════════════════════════════════════════════════════════════

  {
    name: "Q Balls",
    address: "Kumaharan Gali, Main Bazar, Aram Bagh, Paharganj, New Delhi, Delhi 110055",
    area: "Paharganj",
    city: "New Delhi",
    lat: 28.641618,
    lng: 77.2156585,
    rating: 4.3,
    phone: null,
    openingHours: "11:00 AM – 12:00 AM",
    snookerTables: 2,
    poolTables: 1,
    snookerPricePerHour: 250,
    poolPricePerHour: 180,
    amenities: ["Canteen", "Tea & Coffee", "Friendly Owner"],
  },
  {
    name: "M Snooker and Pool Lounge",
    address: "51/2, Old Rajinder Nagar, Block 51, Rajinder Nagar, New Delhi, Delhi 110060",
    area: "Rajinder Nagar",
    city: "New Delhi",
    lat: 28.641483,
    lng: 77.1880116,
    rating: 4.5,
    phone: "+91 99996 00082",
    openingHours: "11:00 AM – 10:00 PM",
    snookerTables: 4,
    poolTables: 2,
    snookerPricePerHour: 300,
    poolPricePerHour: 200,
    amenities: ["AC", "Premium S1 Tables", "Heated Tables", "Good Ambience"],
  },
  {
    name: "Delhi Snooker Club",
    address: "Block D, Krishna Nagar, Delhi 110051",
    area: "Krishna Nagar",
    city: "New Delhi",
    lat: 28.6600357,
    lng: 77.2810453,
    rating: 4.8,
    phone: "+91 70421 78366",
    openingHours: "Open 24 hours",
    snookerTables: 4,
    poolTables: 2,
    snookerPricePerHour: 280,
    poolPricePerHour: 200,
    amenities: ["AC", "24/7", "Luxury Tables", "Good Food", "Classy Ambience"],
  },
  {
    name: "CUE TIP Snooker and Pool Academy",
    address: "Basement, B-224, Dr Ramlal Verma Marg, Block B, Lajpat Nagar I, New Delhi, Delhi 110024",
    area: "Lajpat Nagar",
    city: "New Delhi",
    lat: 28.5756903,
    lng: 77.2413901,
    rating: 4.6,
    phone: "+91 11 4107 4426",
    openingHours: "9:00 AM – 11:00 PM",
    snookerTables: 3,
    poolTables: 4,
    snookerPricePerHour: 300,
    poolPricePerHour: 200,
    amenities: ["AC", "Food & Pizza", "Coaching", "Chicken Momos"],
  },
  {
    name: "Cue Masterz Snooker & Pool Center",
    address: "2nd Floor, Gupta Building, 9062, Ram Bagh Rd, Azad Market, Tis Hazari, New Delhi, Delhi 110006",
    area: "Azad Market, Tis Hazari",
    city: "New Delhi",
    lat: 28.6654997,
    lng: 77.2052398,
    rating: 4.5,
    phone: "+91 87448 75701",
    openingHours: "5:00 PM – 5:00 AM",
    snookerTables: 3,
    poolTables: 2,
    snookerPricePerHour: 250,
    poolPricePerHour: 180,
    amenities: ["Late Night", "Good Hospitality"],
  },
  {
    name: "THE CUE WORLD",
    address: "Basement, Backside of NHI Hospital, Community Centre, 48/1, D Block, East of Kailash, New Delhi, Delhi 110065",
    area: "East of Kailash",
    city: "New Delhi",
    lat: 28.5574541,
    lng: 77.2456791,
    rating: 4.3,
    phone: "+91 99106 73232",
    openingHours: "Open 24 hours",
    snookerTables: 2,
    poolTables: 1,
    snookerPricePerHour: 250,
    poolPricePerHour: 180,
    amenities: ["AC", "24/7", "Friendly Owner"],
  },
  {
    name: "The Masters Snooker Club",
    address: "198, 14 Basement, Ramesh Market, Garhi Jharia Maria, East of Kailash, New Delhi, Delhi 110065",
    area: "East of Kailash",
    city: "New Delhi",
    lat: 28.5597494,
    lng: 77.2476663,
    rating: 5.0,
    phone: "+91 88608 81318",
    openingHours: "11:00 AM – 4:00 AM",
    snookerTables: 2,
    poolTables: 1,
    snookerPricePerHour: 250,
    poolPricePerHour: 180,
    amenities: ["AC", "Late Night", "Friendly Staff"],
  },
  {
    name: "Alpha Cue – Snooker Club",
    address: "122-B, Nehru Enclave, Kalkaji, New Delhi, Delhi 110019",
    area: "Kalkaji, Nehru Enclave",
    city: "New Delhi",
    lat: 28.5425741,
    lng: 77.2508091,
    rating: 4.7,
    phone: "+91 99991 65116",
    openingHours: "11:00 AM – 11:00 PM",
    snookerTables: 4,
    poolTables: 2,
    snookerPricePerHour: 300,
    poolPricePerHour: 200,
    amenities: ["AC", "Food & Drinks", "IPL Screening", "Professional Tables", "Coaching"],
  },
  {
    name: "Snooker Arena",
    address: "Basement, 14/2, Kalkaji Extension, Kalkaji, New Delhi, Delhi 110019",
    area: "Kalkaji Extension",
    city: "New Delhi",
    lat: 28.5411317,
    lng: 77.2526224,
    rating: 4.9,
    phone: "+91 83680 97920",
    openingHours: "Open 24 hours",
    snookerTables: 3,
    poolTables: 2,
    snookerPricePerHour: 250,
    poolPricePerHour: 180,
    amenities: ["AC", "24/7", "PS5", "Good Food", "Affordable"],
  },
  {
    name: "The Snook House Cafe",
    address: "First Floor, Kailash Colony Market, HS-25, Kailash Colony, Greater Kailash, New Delhi, Delhi 110048",
    area: "Kailash Colony, Greater Kailash",
    city: "New Delhi",
    lat: 28.5537109,
    lng: 77.2408049,
    rating: 4.6,
    phone: "+91 11 4109 1991",
    openingHours: "12:00 PM – 1:00 AM",
    snookerTables: 2,
    poolTables: 2,
    snookerPricePerHour: 300,
    poolPricePerHour: 220,
    amenities: ["Café", "Food Menu", "Drinks", "Late Night", "Good Vibe"],
  },
  {
    name: "The Snooker City",
    address: "247, 3rd Floor, Backside Sant Nagar, East of Kailash, New Delhi, Delhi 110065",
    area: "Sant Nagar, East of Kailash",
    city: "New Delhi",
    lat: 28.5556333,
    lng: 77.2490926,
    rating: 4.0,
    phone: "+91 98732 88800",
    openingHours: "12:00 PM – 5:00 AM",
    snookerTables: 2,
    poolTables: 1,
    snookerPricePerHour: 240,
    poolPricePerHour: 180,
    amenities: ["Late Night", "Wiraka Tables"],
  },
  {
    name: "The Gaming Dojo",
    address: "5/31 Basement, Vikram Vihar, Lajpat Nagar 4, New Delhi, Delhi 110024",
    area: "Lajpat Nagar 4, Amar Colony",
    city: "New Delhi",
    lat: 28.5633696,
    lng: 77.2393179,
    rating: 4.9,
    phone: "+91 93115 77757",
    openingHours: "11:00 AM – 2:00 AM",
    snookerTables: 2,
    poolTables: 2,
    snookerPricePerHour: 300,
    poolPricePerHour: 200,
    amenities: ["PS5 Gaming", "Café", "120Hz TV", "Late Night", "Comfortable Seating"],
  },
  {
    name: "Oxzypool & Snooker Centre",
    address: "2nd Floor, SE-6A Extension, near Oxzy Gym, Singalpur Village, West Shalimar Bagh, Delhi 110088",
    area: "Shalimar Bagh",
    city: "New Delhi",
    lat: 28.7042851,
    lng: 77.1564211,
    rating: 4.1,
    phone: "+91 98113 68935",
    openingHours: "5:00 AM – 11:00 PM",
    snookerTables: 3,
    poolTables: 2,
    snookerPricePerHour: 200,
    poolPricePerHour: 120,
    amenities: ["Early Opening", "Budget Friendly"],
  },
  {
    name: "Aroplay",
    address: "1st Floor, Deep Market, Building No. 17, adjacent to Canara Bank, near Bansal Corner, Ashok Vihar, New Delhi, Delhi 110052",
    area: "Ashok Vihar",
    city: "New Delhi",
    lat: 28.6934071,
    lng: 77.1722569,
    rating: 5.0,
    phone: "+91 99539 53902",
    openingHours: "10:00 AM – 2:00 AM",
    snookerTables: 2,
    poolTables: 2,
    snookerPricePerHour: 250,
    poolPricePerHour: 180,
    amenities: ["PS5 Gaming", "Food & Drinks", "Clean Air", "No Smoking", "Female Friendly", "Late Night"],
  },
  {
    name: "Rest & Cue Snooker",
    address: "A/4, Gujranwala Town Part 1, Model Town, Gujranwala Town, New Delhi, Delhi 110033",
    area: "Gujranwala Town",
    city: "New Delhi",
    lat: 28.6985872,
    lng: 77.1858443,
    rating: 5.0,
    phone: null,
    openingHours: "9:00 AM – 11:00 PM",
    snookerTables: 3,
    poolTables: 1,
    snookerPricePerHour: 200,
    poolPricePerHour: 150,
    amenities: ["Good Facilities", "Friendly Crowd"],
  },
  {
    name: "Stopshot Snooker & Cafe",
    address: "DU-13 Basement, near Chaska Restaurant, Block DU, Uttari Pitampura, Pitampura, New Delhi, Delhi 110034",
    area: "Pitampura",
    city: "New Delhi",
    lat: 28.7155702,
    lng: 77.1437813,
    rating: 4.9,
    phone: "+91 88604 03010",
    openingHours: "10:00 AM – 2:00 AM",
    snookerTables: 4,
    poolTables: 2,
    snookerPricePerHour: 300,
    poolPricePerHour: 300,
    amenities: ["AC", "Café", "Late Night", "Fresh Food & Drinks", "Premium Tables"],
  },
  {
    name: "Northern Snooker",
    address: "Basement, Kotak Mahindra Bank, HP-9, opposite Gopal Mandir Marg, Maurya Enclave, Pitampura, New Delhi, Delhi 110034",
    area: "Pitampura, Maurya Enclave",
    city: "New Delhi",
    lat: 28.702435,
    lng: 77.1477041,
    rating: 4.3,
    phone: "+91 79829 93566",
    openingHours: "11:00 AM – 9:00 PM",
    snookerTables: 6,
    poolTables: 2,
    snookerPricePerHour: 150,
    poolPricePerHour: 120,
    amenities: ["Smooth Tables", "Budget Friendly", "Multiple Tables"],
  },
  {
    name: "SNOOKER HUB",
    address: "Basement B-1244, nearby Haryana Sweets, Block B, Shastri Nagar, Delhi 110052",
    area: "Shastri Nagar",
    city: "New Delhi",
    lat: 28.6735461,
    lng: 77.1796339,
    rating: 5.0,
    phone: "+91 88026 28028",
    openingHours: "Open 24 hours",
    snookerTables: 3,
    poolTables: 2,
    snookerPricePerHour: 200,
    poolPricePerHour: 150,
    amenities: ["AC", "24/7", "PS5", "Coaching", "Snacks"],
  },
  {
    name: "Red Ball International",
    address: "A-199 Basement, below Bajaj Showroom, Gujranwala Town Part 1, New Delhi, Delhi 110033",
    area: "Gujranwala Town",
    city: "New Delhi",
    lat: 28.7005595,
    lng: 77.1840466,
    rating: 4.5,
    phone: "+91 89296 33777",
    openingHours: "9:00 AM – 11:00 PM",
    snookerTables: 4,
    poolTables: 3,
    snookerPricePerHour: 250,
    poolPricePerHour: 180,
    amenities: ["AC", "Café", "Hookah", "PS4/Xbox", "Premium Interior", "Lounge"],
  },
  {
    name: "Snooker Town",
    address: "Near B-926, Mother Dairy Rd, Block D, Shastri Nagar, Delhi 110052",
    area: "Shastri Nagar",
    city: "New Delhi",
    lat: 28.6731911,
    lng: 77.1824373,
    rating: 5.0,
    phone: null,
    openingHours: "10:00 AM – 11:00 PM",
    snookerTables: 3,
    poolTables: 1,
    snookerPricePerHour: 200,
    poolPricePerHour: 150,
    amenities: ["Cool Vibe", "Friendly Crowd"],
  },
];

// ─── Seed ────────────────────────────────────────────────────────────────────

async function main() {
  console.log("🎱 Seeding Delhi NCR snooker & pool clubs…\n");

  // Create a dummy owner to associate all seeded clubs with
  const owner = await prisma.user.upsert({
    where: { email: 'seedowner@cueking.com' },
    update: {},
    create: {
      email: 'seedowner@cueking.com',
      name: 'Seed Master Owner',
      role: 'CLUB_OWNER',
    }
  });

  const OWNER_ID = owner.id;
  console.log(`👤 Assigned Owner: ${OWNER_ID}`);

  for (const raw of clubs) {
    const { open, close } = parseTime(raw.openingHours);

    // 1. Upsert Location
    const existingLoc = await prisma.location.findFirst({
      where: { city: raw.city, area: raw.area },
    });
    
    const locationId = existingLoc
      ? existingLoc.id
      : (await prisma.location.create({ data: { city: raw.city, area: raw.area } })).id;

    // 2. Upsert Club
    const existingClub = await prisma.club.findFirst({
      where: { name: raw.name, locationId },
    });

    let clubId: string;
    if (existingClub) {
      clubId = existingClub.id;
      await prisma.club.update({
        where: { id: clubId },
        data: {
          rating: raw.rating,
          fullAddress: raw.address,
          lat: raw.lat,
          lng: raw.lng,
          openingTime: open,
          closingTime: close,
          amenities: raw.amenities,
        },
      });
      console.log(`  ♻️  Updated  : ${raw.name}`);
    } else {
      const club = await prisma.club.create({
        data: {
          name: raw.name,
          fullAddress: raw.address,
          rating: raw.rating,
          lat: raw.lat,
          lng: raw.lng,
          openingTime: open,
          closingTime: close,
          amenities: raw.amenities,
          ownerId: OWNER_ID,
          locationId,
        },
      });
      clubId = club.id;
      console.log(`  ✅  Created  : ${raw.name}`);
    }

    // 3. Seed TableCategories
    const categories: { name: string; quantity: number; pricePerHour: number }[] = [];

    if (raw.snookerTables && raw.snookerTables > 0) {
      categories.push({
        name: "Snooker Table",
        quantity: raw.snookerTables,
        pricePerHour: raw.snookerPricePerHour,
      });
    }
    if (raw.poolTables && raw.poolTables > 0) {
      categories.push({
        name: "8 Ball Pool Table",
        quantity: raw.poolTables,
        pricePerHour: raw.poolPricePerHour,
      });
    }

    for (const cat of categories) {
      const existing = await prisma.tableCategory.findFirst({
        where: { clubId, name: cat.name },
      });
      if (!existing) {
        await prisma.tableCategory.create({
          data: { ...cat, clubId },
        });
      } else {
        await prisma.tableCategory.update({
          where: { id: existing.id },
          data: { quantity: cat.quantity, pricePerHour: cat.pricePerHour },
        });
      }
    }
  }

  console.log(`\n🎉 Done! ${clubs.length} clubs seeded.`);
}

main()
  .catch((e) => {
    console.error(e);
    // @ts-ignore
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
